import manzana from "./../Imagenes/manzanas.jpeg" ;

export const filas = [
    {
        producto: "manzana",
        cantidad: 5,precio: 2.50,
        tienda: "Supermercado A",
        notas: "Manzanas verdes",
        comprado: false,
        imagen: manzana
    },
    {
        producto: "Leche",
        cantidad: 2,
        precio: 1.20,
        tienda: "Tienda de lacteos",
        notas: "Leche desnatada",
        comprado: true,
        imagen: "./../Imagenes/Leche.jpg",
    },
    {
        producto: "Pan",
        cantidad: 1,
        precio: 2.00,
        tienda: "Panaderia B",
        notas: "Pan integral",
        comprado: false,
        imagen: "./../Imagenes/Pan.jpg",
    },
    {
        producto: "Huevos",
        cantidad: 12,
        precio: 3.50,
        tienda: "Granja fresh",
        notas: "Huevos organicos",
        comprado: false,
        imagen: "./../Imagenes/Huevos.jpg",
    },
    {
        producto: "Pollo",
        cantidad: 1,
        precio: 7.99,
        tienda: "Carniceria B",
        notas: "Pechuga de pollo",
        comprado: false,
        imagen: "./../Imagenes/Pollo.jpeg",
    },
    {
        producto: "Cereal",
        cantidad: 3,
        precio: 4.75  ,
        tienda: "Panaderia B",
        notas: "Pan integral",
        comprado: false,
        imagen: "./../Imagenes/Pan.jpg",
    },
    {
        producto: "Tomates",
        cantidad: 6,
        precio: 2.00  ,
        tienda: "Fruteria B",
        notas: "Tomates organicos",
        comprado: false,
        imagen: "./../Imagenes/tomates.jpg",
    },
    {
        producto: "Pasta",
        cantidad: 4,
        precio: 1.50  ,
        tienda: "Tienda de comestibles",
        notas: "Jabon liquido",
        comprado: false,
        imagen: "./../Imagenes/jabon.jpg",
    },
    {
        producto: "Agua",
        cantidad: 1,
        precio: 0.75  ,
        tienda: "Gasolinera B",
        notas: "Botella de agua",
        comprado: false,
        imagen: "./../Imagenes/agua.jpg",
    },
  ];